apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdbinstances.otc
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: DbInstance

  mode: Pipeline

  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform

      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources

        resources:
          - name: secret
            base:
              apiVersion: v1
              kind: Secret
              metadata:
                name: example-rds-secret
                namespace: test
              type: Opaque
              data:
                example-rds-key: "UG9zdGdyZXNAIzIwMjQ="

          - name: vpc
            base:
              apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
              kind: VpcV1
              metadata:
                namespace: test
              spec:
                forProvider:
                  cidr: "192.168.0.0/16"
                  name: crossplane-rds-vpc
                  tags:
                    managed-by: crossplane
          - name: subnet
            base:
              apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
              kind: SubnetV1
              metadata:
                namespace: test
              spec:
                forProvider:
                  cidr: "192.168.0.0/16"
                  gatewayIp: "192.168.0.1"
                  name: crossplane-rds-subnet
                  ntpAddresses: "10.100.0.33,10.100.0.34"
                  vpcIdSelector:
                    matchControllerRef: true
                  tags:
                    managed-by: crossplane
          - name: security-group
            base:
              apiVersion: compute.opentelekomcloud.m.crossplane.io/v1alpha1
              kind: SecgroupV2
              metadata:
                namespace: test
              spec:
                forProvider:
                  description: crossplane security group
                  name: crossplane-rds-sg
                  rule:
                    - cidr: 0.0.0.0/0
                      fromPort: 8635
                      ipProtocol: tcp
                      toPort: 8635
                    - cidr: 0.0.0.0/0
                      fromPort: 8080
                      ipProtocol: tcp
                      toPort: 8080
                    - cidr: 0.0.0.0/0
                      fromPort: 443
                      ipProtocol: tcp
                      toPort: 443
          - name: eip
            base:
              apiVersion: vpc.opentelekomcloud.m.crossplane.io/v1alpha1
              kind: EIPV1
              metadata:
                namespace: test
              spec:
                forProvider:
                  bandwidth:
                    - chargeMode: traffic
                      name: crossplane-rds-instance
                      shareType: PER
                      size: 8
                  publicip:
                    - type: 5_bgp
          - name: rds
            base:
              apiVersion: rds.opentelekomcloud.m.crossplane.io/v1alpha1
              kind: InstanceV3
              metadata:
                namespace: test
              spec:
                forProvider:
                  availabilityZone:
                    - eu-de-03

                  backupStrategy:
                    - keepDays: 1
                      startTime: 08:00-09:00

                  db:
                    - passwordSecretRef:
                        name: example-rds-secret
                        key: example-rds-key
                      port: 8635
                      type: PostgreSQL
                      version: "15"

                  flavor: rds.pg.n1.large.2

                  name: default

                  tags:
                    managed-by: crossplane

                  volume:
                    - size: 100
                      type: CLOUDSSD

                  vpcIdSelector:
                    matchControllerRef: true

                  subnetIdSelector:
                    matchControllerRef: true

                  computeSecurityGroupIdSelector:
                    matchControllerRef: true

                  publicIpsSelector:
                    matchControllerRef: true

            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: spec.forProvider.name

              - type: FromCompositeFieldPath
                fromFieldPath: spec.availabilityZone
                toFieldPath: spec.forProvider.availabilityZone[0]

              - type: FromCompositeFieldPath
                fromFieldPath: spec.sizeClass
                toFieldPath: spec.forProvider.flavor
                transforms:
                  - type: map
                    map:
                      small: rds.pg.n1.large.2
                      large: rds.pg.n1.large.4

              - type: FromCompositeFieldPath
                fromFieldPath: spec.size
                toFieldPath: spec.forProvider.volume[0].size
